name: "Bug Report"
description: Create a new ticket for a bug.
title: "[BUG]: "
labels: [
  "bug"
]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this bug report!**

        Please search to see if an issue already exists for your bug. If you find a similar issue, please add a comment to the existing issue instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Description of the bug
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue if applicable
      value: |
        1. Select '...'
        2. Click on '...'
        3. Go to '...'
        4. See error
      render: bash
    validations:
      required: false
  - type: dropdown
    id: affected
    attributes:
      label: "Affected area"
      description: What area of the application is affected?
      multiple: true
      options:
        - Crash
        - Visual
        - Functionality
        - Performance
        - Security
        - Translation
        - Not starting
        - Not installing
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste the logs of the application if applicable
      render: bash
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What operating system are you using?
      multiple: false
      options:
        - Windows 10
        - Windows 11
        - Mac
        - Linux
        - Other
    validations:
      required: true
