name: Feature Request
description: Create a new ticket for a feature request.
title: "[REQUEST]: "
labels: [
  "feature"
]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this feature request!**

        Please search to see if an issue already exists for your bug. If you find a similar issue, please add a comment to the existing issue instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description of the Feature
      description: Detailed description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: Describe how you would like the feature to work.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or relevant information about the feature request.
    validations:
      required: false

